# Generated by Django 4.2.3 on 2023-07-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_conta_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
